version: '3'
services: 
    ## container one
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    ## container two
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            ## using '-' because it essential representing the array
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
